ForexProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),
                  path('', include('common_app.urls')),
                  path('currencies/', include('currencies.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include

from accounts import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/',views.login_view,name='login'),
    path('profile/', views.profile, name='user-profile'),
    path('edit_profile/', views.profile_edit, name='edit-profile'),
    path('delete_profile/', views.profile_delete, name='delete-profile'),
    path('change_password/', views.change_password, name='password_change'),
    path('change_password/done/', views.change_password_done, name='password_change_done'),

]

currencies/urls.py
from django.urls import path, include

from currencies import views

urlpatterns = [
    path('add_currency/', views.CurrencyCreateView.as_view(), name='add currency'),
    path('edit_currency/<int:pk>/', views.CurrencyUpdateView.as_view(), name='edit currency'),
    path('all_currency/', views.CurrencyAllView.as_view(), name='all_currency'),
    path('detail_currency/<int:pk>/', views.CurrencyDetailView.as_view(), name='detail currency'),
    path('delete_currency/<int:pk>/', views.CurrencyDeleteView.as_view(), name='delete currency'),
    path('live_quotes/', views.currencies_live_quotes, name='live quotes'),
    path('add_category/', views.CategoryCreateView.as_view(), name='add category'),
    path('edit_categry/<int:pk>/', views.CategoryUpdateView.as_view(), name='edit category'),
    path('delete_categry/<int:pk>/', views.CategoryDeleteView.as_view(), name='delete category'),
    path('add_links/', views.LinkCreateView.as_view(), name='add links'),
    path('all_links/', views.LinkAllView.as_view(), name='all links'),
    path('links_edit/<int:pk>/', views.LinkUpdateView.as_view(), name='edit links'),
    path('links_delete/<int:pk>/', views.LinkDeleteView.as_view(), name='delete links'),
]

currencies/models.py
from django.db import models


# Create your models here.
class Currency(models.Model):
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=5)
    central_bank = models.CharField(max_length=100)
    current_interest_rate = models.URLField()
    currency_history = models.TextField()
    picture = models.ImageField(upload_to='currency_pics', blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'{self.name}'


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


class Links(models.Model):
    description = models.CharField(max_length=200)
    link = models.URLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'I`m in {self.category.name} category'

currencies/forms.py
from django import forms
from django.core.exceptions import ValidationError

from django.core.validators import URLValidator
from currencies.models import Currency, Category, Links


class CurrencyForm(forms.ModelForm):
    use_required_attribute = False

    name = forms.CharField(widget=forms.TextInput())
    current_interest_rate = forms.URLField(widget=forms.URLInput())
    currency_history = forms.CharField(widget=forms.Textarea())
    picture = forms.ImageField(required=False)

    class Meta:
        model = Currency
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    use_required_attribute = False

    class Meta:
        model = Category
        fields = '__all__'


class LinksForm(forms.ModelForm):
    use_required_attribute = False

    class Meta:
        model = Links
        fields = '__all__'

currencies/views.py
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from currencies.forms import CurrencyForm, CategoryForm, LinksForm
from currencies.models import Currency, Category, Links


@login_required
def currencies_live_quotes(request):
    params = {
        'token': 'y4uhurw5suke60rirzzd',
        'currency': 'EUR/USD USD/JPY GBP/USD AUD/USD USD/CAD'
    }
    api_result = requests.get('https://currencydatafeed.com/api/data.php', params)

    api_response = api_result.json()
    currencies = api_response['currency']
    context = {'currencies': currencies}
    return render(request, 'currencies/quotes.html', context)


class CurrencyCreateView(LoginRequiredMixin, CreateView):
    model = Currency
    form_class = CurrencyForm
    template_name = 'currencies/currency_add.html'

    def form_valid(self, form):
        currency = form.save(commit=False)
        currency.save()
        return redirect('all_currency')


class CurrencyDetailView(LoginRequiredMixin, DetailView):
    model = Currency
    context_object_name = 'currency'
    template_name = 'currencies/currency_detail.html'


class CurrencyUpdateView(LoginRequiredMixin, UpdateView):
    model = Currency
    form_class = CurrencyForm
    template_name = 'currencies/currency_edit.html'

    def form_valid(self, form):
        currency = form.save(commit=False)
        currency.save()
        return redirect('detail currency', currency.pk)


class CurrencyDeleteView(LoginRequiredMixin, DeleteView):
    model = Currency
    success_url = reverse_lazy('all_currency')
    template_name = 'currencies/currency_delete.html'


class CurrencyAllView(LoginRequiredMixin, ListView):
    model = Currency
    context_object_name = 'currencies'
    template_name = 'currencies/currency_all.html'
    paginate_by = 3


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'currencies/category_add.html'

    def form_valid(self, form):
        category = form.save(commit=False)
        category.save()
        return redirect('all links')


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'currencies/category_edit.html'

    def form_valid(self, form):
        category = form.save(commit=False)
        category.save()
        return redirect('all links')


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('all links')
    template_name = 'currencies/category_delete.html'
    context_object_name = 'category'


class LinkCreateView(LoginRequiredMixin, CreateView):
    model = Links
    form_class = LinksForm
    template_name = 'currencies/links_add.html'

    def form_valid(self, form):
        links = form.save(commit=False)
        links.save()
        return redirect('all links')


class LinkAllView(LoginRequiredMixin, ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'currencies/links_all.html'
    paginate_by = 2

    def get_queryset(self):
        return Category.objects.all()


class LinkUpdateView(LoginRequiredMixin, UpdateView):
    model = Links
    form_class = LinksForm
    template_name = 'currencies/links_edit.html'

    def form_valid(self, form):
        link = form.save(commit=False)
        link.save()
        return redirect('all links')


class LinkDeleteView(LoginRequiredMixin, DeleteView):
    model = Links
    success_url = reverse_lazy('all links')
    template_name = 'currencies/links_delete.html'
    context_object_name = 'link'

templates/currencies/category_add.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="POST" action="">
                <h3>Add category:</h3>
                {% csrf_token %}
                {{ form|crispy }}



                <button type="submit" class="btn btn-secondary">Add</button>
                <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/currencies/category_delete.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <form method="POST" action="">
        <h3 class="text-center">Are you sure you want to delete "{{ category.name }}"?</h3>
        {% csrf_token %}
        <br>
        <div class="text-center">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
        </div>

    </form>
{% endblock %}

templates/currencies/category_edit.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="POST" action="">
                <h3>Edit your category here</h3>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Save</button>
                <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/currencies/currency_add.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="" enctype="multipart/form-data">

                {% csrf_token %}
                <h2>Add currency:</h2>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.name|as_crispy_field }}

                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.symbol|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.central_bank|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.current_interest_rate|as_crispy_field }}


                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.currency_history|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">


                        {{ form.picture|as_crispy_field }}
                    </div>

                </div>

                <button type="submit" class="btn btn-secondary">Add</button>
                <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/currencies/currency_all.html
{% extends 'common_app/base.html' %}
{% load static %}
{% block body_block %}
    <link rel="stylesheet" href="{% static 'accounts/css/profile_pic.css' %}"/>
    <div class="container">
        <h1 class='text-center'>Currencies</h1>
        {% if currencies %}
            <div class="row">
                {% for currency in currencies %}
                    <div class="col-lg-4">
                        <br>
                        <div class="card" style="width: 18rem;">
                            {% if currency.picture %}
                                <img src="{{ currency.picture.url }}" alt="Place for picture">
                            {% else %}
                                <img id="user_pic" src="{% static 'accounts/images/default_user.png' %}" alt="">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ currency.symbol }} </h5>

                                <a href="{% url 'detail currency' currency.pk %}" class="btn btn-secondary">See
                                    details</a>
                            </div>

                        </div>
                        <br>
                    </div>
                {% endfor %}

            </div>
            {% if is_paginated %}
                <br>
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                         <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="">Next</a>
                    {% endif %}
                </ul>

        {% endif %}
        {% else %}
            <br>
            <h3 class="text-center">There are no currencies added!</h3>
            {% if request.user.is_superuser %}
                <div class="text-center">
                    <a href="{% url 'add currency' %}"><big>Add currency</big></a>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/currencies/currency_delete.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
     <form method="POST" action="">
    <h3>Are you sure you want to delete "{{ currency.name }}" from currencies list ?</h3>
        {% csrf_token %}
        <br>
     <button type="submit" class="btn btn-danger">Delete</button>
    <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
    </form>
{% endblock %}

templates/currencies/currency_detail.html
{% extends 'common_app/base.html' %}
{% load static %}
{% block body_block %}

    <div class="row justify-content-center">
        <div class="col-8">

            <div class="jumbotron text-center blue-grey lighten-5">
                {% if currency.picture %}
                    <img src="{{ currency.picture.url }}" alt="Place for picture">
                {% else %}
                    <img id="user_pic" src="{% static 'accounts/images/default_user.png' %}" alt="">
                {% endif %}
                <h4 class="card-title h4"> Name : {{ currency.name }}</h4>
                <p class="indigo-text my-4 font-weight-bold">Symbol : {{ currency.symbol }}</p>
                <p class="indigo-text my-4 font-weight-bold">Central Bank : {{ currency.central_bank }}</p>
                <a href="{{ currency.current_interest_rate }}" class="green-text" target="_blank">
                    <h6 class="h6 pb-1"><i class="fas fa-desktop pr-1"></i>See current interest rate here</h6>
                </a>

                <div class="row d-flex justify-content-center">
                    <div class="col-xl-7 pb-2">
                        <p class="card-text">{{ currency.currency_history }}</p>
                    </div>
                </div>
                <hr class="my-4 pb-2">
                {% if request.user.is_superuser %}
                    <a class="btn blue-gradient btn-rounded" style="color: blue"
                       href="{% url 'edit currency' currency.pk %}">Edit<i
                            class="far fa-gem ml-1"></i>
                    </a>
                    <a class="btn btn-indigo btn-rounded" style="color: red"
                       href="{% url 'delete currency' currency.pk %}">Delete<i
                            class="fas fa-download ml-1"></i>
                    </a>
                {% endif %}
                <a class="btn btn-indigo btn-rounded" style="color: black" href="{% url 'all_currency' %}">See all
                    currencies<i
                            class="fas fa-download ml-1"></i>


            </div>

        </div>
    </div>
{% endblock %}

templates/currencies/currency_edit.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="" enctype="multipart/form-data">

                {% csrf_token %}
                <h2>Edit currency:</h2>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.symbol|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.central_bank|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.current_interest_rate|as_crispy_field }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.currency_history|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">


                        {{ form.picture|as_crispy_field }}
                    </div>

                </div>

                <button type="submit" class="btn btn-secondary">Save</button>
                <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/currencies/links_add.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="POST" action="">
                <h3>Add link:</h3>
                {% csrf_token %}
                {{ form|crispy }}


                <button type="submit" class="btn btn-secondary">Add</button>
                <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/currencies/links_all.html
{% extends 'common_app/base.html' %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-8">
            {% if categories %}
                {% for category in categories %}
                    <br>
                    <h3 class="text-left" style="color:brown">{{ category.name }} {% if request.user.is_superuser %}
                        <span>
                                    <a class="btn blue-gradient btn-rounded" style="color: darkgreen"
                                       href="{% url 'edit category' category.pk %}">Edit<i
                                            class="far fa-gem ml-1"></i>
                                    </a>
                                    <a class="btn btn-indigo btn-rounded" style="color: red"
                                       href="{% url 'delete category' category.pk %}">Delete<i
                                            class="fas fa-download ml-1"></i>
                                    </a>
                                </span>
                    {% endif %}</h3>
                    <hr>
                    <ul>
                        {% for l in category.links_set.all %}
                            <br>
                            <li><h5>Description: {{ l.description }} <a href="{{ l.link }}" target="_blank">
                                Link</a>
                                {% if request.user.is_superuser %}
                                    <span>
                                    <a class="btn blue-gradient btn-rounded" style="color: darkgreen"
                                       href="{% url 'edit links' l.pk %}">Edit<i
                                            class="far fa-gem ml-1"></i>
                                    </a>
                                    <a class="btn btn-indigo btn-rounded" style="color: red"
                                       href="{% url 'delete links' l.pk %}">Delete<i
                                            class="fas fa-download ml-1"></i>
                                    </a>
                                </span>
                                {% endif %}
                            </h5></li>
                            <hr>
                        {% endfor %}
                    </ul>
                    <hr>
                {% endfor %}
                {% if is_paginated %}
                    <br>
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                            <a class="page-link" href="">Next</a>
                        {% endif %}
                    </ul>

                {% endif %}
            {% else %}
                <h4 class="text-center">There are no links added!</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/currencies/links_delete.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <form method="POST" action="">
        <h3 class="text-center">Are you sure you want to delete "{{ link.link }}" from {{ link.category}} ?</h3>
        {% csrf_token %}
        <br>
        <div class="text-center">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
        </div>

    </form>
{% endblock %}

templates/currencies/links_edit.html
{% extends 'common_app/base.html' %}
{% load crispy_forms_filters %}
{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="POST" action="">
                <h3>Edit your link here</h3>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Save</button>
                <a class="btn btn-success" href="javascript:history.back()">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/currencies/quotes.html
{% extends 'common_app/base.html' %}


{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-8">
            <h3 class="text-center">Live currency quotes</h3>
            <br>
            <table id="dtBasicExample" class="table">
                <thead>
                <tr>
                    <th class="th-sm">Name
                    </th>
                    <th class="th-sm">Position
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for curr in currencies %}
                    <tr>

                        <td>{{ curr.currency }}</td>
                        <td>{{ curr.value }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}